from dataclasses import dataclass, field

@dataclass
class Stats:
    AP: float = field(default=0, init=False)
    Add: float = field(default=0, init=False)
    Atkspeed: float = field(default=0, init=False)
    AwkCDR: float = field(default=0, init=False)
    CDR_Flat: float = field(default=0, init=False)
    CDR1: float = field(default=0, init=False)
    CDR2: float = field(default=0, init=False)
    CDmg: float = field(default=0, init=False)
    ChargeAS: float = field(default=0, init=False)
    Crit: float = field(default=0, init=False)
    DefRed: float = field(default=0, init=False)
    HBCDdmg: float = field(default=0, init=False)
    HCAS: float = field(default=0, init=False)
    MCDmg: float = field(default=0, init=False)
    MainStat: float = field(default=0, init=False)
    Movespeed: float = field(default=0, init=False)
    SkillCDR: float = field(default=0, init=False)
    WpnPower: float = field(default=0, init=False)
    AwkMult: float = field(default=1, init=False)
    Back: float = field(default=1, init=False)
    Charge: float = field(default=1, init=False)
    Exec: float = field(default=1, init=False)
    HC: float = field(default=1, init=False)
    HM: float = field(default=1, init=False)
    Head: float = field(default=1, init=False)
    HeadBack: float = field(default=1, init=False)
    Mult: float = field(default=1, init=False)
    SkillMult: float = field(default=1, init=False)
    
